<a href="https://colab.research.google.com/github/murtazaarsh7/ml_in_summers2026/blob/main/assignment_lecture4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [7]:
import pandas as pd
import numpy as np
import csv

In [8]:
df=pd.read_csv("/content/IMDB Dataset.csv", encoding='latin-1', sep=',', engine='python', on_bad_lines='skip')

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
import re

In [11]:
clean = re.compile('<.*?>')

def remove_html_tags(text):
    # Substitute the tags with an empty string
    return re.sub(clean, '', text)

In [12]:
remove_html_tags(df.review[1])

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [13]:
df["review"]=df["review"].str.lower()

In [14]:
df["review"]=df["review"].apply(remove_html_tags)

In [15]:
df["review"][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [16]:
import string

In [17]:
exclude=string.punctuation

In [18]:
def remove_punc(text):
  for char in exclude:
    text.replace(char,'')
  return text

In [19]:
df['review']=df['review'].apply(remove_punc)

In [20]:
df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [21]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [22]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [23]:
def remove_stop_words(text):
  new_text=[]
  for word in text.split():
    if word not in stop_words:
      new_text.append(word)

  return " ".join(new_text)

In [24]:
df['review']=df['review'].apply(remove_stop_words)

In [25]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. filming technique...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 50000, dtype: object

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv=CountVectorizer()

In [28]:
bow=cv.fit_transform(df['review'])

In [29]:
print(cv.vocabulary_)

{'one': 66266, 'reviewers': 77936, 'mentioned': 59438, 'watching': 101532, 'oz': 67674, 'episode': 31157, 'hooked': 44347, 'right': 78359, 'exactly': 32058, 'happened': 41818, 'me': 58842, 'the': 93055, 'first': 34722, 'thing': 93406, 'struck': 89396, 'brutality': 13606, 'unflinching': 97831, 'scenes': 81262, 'violence': 100414, 'set': 82885, 'word': 103493, 'go': 39101, 'trust': 96131, 'show': 84048, 'faint': 33035, 'hearted': 42574, 'timid': 94057, 'pulls': 73949, 'punches': 73996, 'regards': 76497, 'drugs': 28436, 'sex': 82986, 'hardcore': 41884, 'classic': 18299, 'use': 99048, 'it': 48543, 'called': 14759, 'nickname': 64247, 'given': 38776, 'oswald': 66941, 'maximum': 58385, 'security': 82235, 'state': 88312, 'penitentary': 69313, 'focuses': 35454, 'mainly': 56805, 'emerald': 30270, 'city': 18139, 'experimental': 32468, 'section': 82214, 'prison': 72949, 'cells': 16281, 'glass': 38856, 'fronts': 36691, 'face': 32905, 'inwards': 48178, 'privacy': 72965, 'high': 43411, 'agenda': 3274, 'em': 30153, 'home': 44122, 'many': 57449, 'aryans': 6577, 'muslims': 62786, 'gangstas': 37487, 'latinos': 53299, 'christians': 17717, 'italians': 48553, 'irish': 48262, 'more': 61748, 'so': 86136, 'scuffles': 81968, 'death': 23856, 'stares': 88212, 'dodgy': 27331, 'dealings': 23825, 'shady': 83120, 'agreements': 3386, 'never': 64032, 'far': 33342, 'away': 7693, 'would': 103657, 'say': 81025, 'main': 56791, 'appeal': 5740, 'due': 28605, 'fact': 32952, 'goes': 39226, 'shows': 84085, 'dare': 23469, 'forget': 35808, 'pretty': 72786, 'pictures': 70384, 'painted': 67889, 'mainstream': 56815, 'audiences': 7286, 'charm': 16843, 'romance': 79029, 'mess': 59643, 'around': 6359, 'ever': 31889, 'saw': 80994, 'nasty': 63388, 'surreal': 90658, 'ready': 75681, 'watched': 101524, 'developed': 25532, 'taste': 92038, 'got': 39638, 'accustomed': 2373, 'levels': 54180, 'graphic': 39946, 'injustice': 47201, 'crooked': 22306, 'guards': 40669, 'who': 102489, 'll': 55001, 'sold': 86363, 'nickel': 64228, 'inmates': 47224, 'kill': 51321, 'order': 66646, 'get': 38300, 'well': 101955, 'mannered': 57352, 'middle': 59982, 'class': 18295, 'turned': 96451, 'bitches': 10926, 'lack': 52653, 'street': 89207, 'skills': 85080, 'experience': 32459, 'may': 58393, 'become': 9481, 'comfortable': 19414, 'uncomfortable': 97302, 'viewing': 100229, 'thats': 93035, 'touch': 94905, 'darker': 23494, 'side': 84363, 'wonderful': 103340, 'little': 54908, 'production': 73121, 'filming': 34436, 'technique': 92311, 'unassuming': 97142, 'old': 66112, 'time': 93998, 'bbc': 9241, 'fashion': 33496, 'gives': 38781, 'comforting': 19417, 'sometimes': 86514, 'discomforting': 26467, 'sense': 82592, 'realism': 75711, 'entire': 30981, 'piece': 70410, 'actors': 2578, 'extremely': 32746, 'chosen': 17659, 'michael': 59885, 'sheen': 83464, 'has': 42126, 'polari': 71450, 'voices': 100708, 'pat': 68700, 'too': 94607, 'truly': 96101, 'see': 82276, 'seamless': 82068, 'editing': 29443, 'guided': 40752, 'references': 76368, 'williams': 102787, 'diary': 25797, 'entries': 31032, 'worth': 103636, 'terrificly': 92793, 'written': 103807, 'performed': 69507, 'masterful': 58063, 'great': 40083, 'master': 58055, 'comedy': 19386, 'life': 54402, 'really': 75739, 'comes': 19402, 'things': 93417, 'fantasy': 33324, 'guard': 40656, 'which': 102305, 'rather': 75432, 'traditional': 95131, 'dream': 28193, 'techniques': 92312, 'remains': 76900, 'solid': 86400, 'disappears': 26358, 'plays': 71057, 'knowledge': 51858, 'senses': 82600, 'particularly': 68547, 'concerning': 19941, 'orton': 66852, 'halliwell': 41476, 'sets': 82902, 'flat': 34972, 'murals': 62661, 'decorating': 24108, 'every': 31926, 'surface': 90586, 'terribly': 92786, 'done': 27573, 'thought': 93579, 'way': 101652, 'spend': 87232, 'hot': 44637, 'summer': 90158, 'weekend': 101815, 'sitting': 84914, 'air': 3536, 'conditioned': 20045, 'theater': 93073, 'light': 54455, 'plot': 71179, 'simplistic': 84677, 'dialogue': 25751, 'witty': 103191, 'characters': 16759, 'likable': 54502, 'even': 31859, 'bread': 12911, 'suspected': 90741, 'serial': 82795, 'killer': 51334, 'disappointed': 26361, 'realize': 75727, 'match': 58127, 'point': 71381, 'risk': 78535, 'addiction': 2679, 'proof': 73337, 'woody': 103423, 'allen': 4037, 'still': 88727, 'fully': 36877, 'control': 20780, 'style': 89594, 'us': 99030, 'grown': 40535, 'love': 55664, 'this': 93476, 'laughed': 53356, 'comedies': 19383, 'years': 104291, 'decade': 23958, 'impressed': 46237, 'scarlet': 81186, 'johanson': 49668, 'managed': 57135, 'tone': 94565, 'sexy': 83036, 'image': 45876, 'jumped': 50068, 'average': 7583, 'spirited': 87381, 'young': 104551, 'woman': 103308, 'crown': 22395, 'jewel': 49415, 'career': 15377, 'wittier': 103184, 'devil': 25575, 'wears': 101731, 'prada': 72273, 'interesting': 47708, 'superman': 90384, 'friends': 36549, 'basically': 8979, 'there': 93254, 'family': 33207, 'boy': 12609, 'jake': 48877, 'thinks': 93432, 'zombie': 105144, 'closet': 18652, 'parents': 68383, 'fighting': 34314, 'movie': 62182, 'slower': 85579, 'soap': 86146, 'opera': 66448, 'suddenly': 89948, 'decides': 24030, 'rambo': 75137, 'ok': 66043, 'going': 39255, 'make': 56877, 'film': 34389, 'must': 62806, 'decide': 24025, 'thriller': 93656, 'drama': 28094, 'watchable': 101518, 'divorcing': 27151, 'arguing': 6169, 'like': 54504, 'real': 75698, 'totally': 94871, 'ruins': 79673, 'expected': 32423, 'boogeyman': 12113, 'similar': 84617, 'instead': 47466, 'meaningless': 58880, 'spots': 87641, '10': 60, 'playing': 71041, 'descent': 25182, 'dialogs': 25750, 'shots': 84009, 'ignore': 45725, 'them': 93158, 'petter': 69897, 'mattei': 58255, 'money': 61357, 'visually': 100561, 'stunning': 89525, 'watch': 101515, 'mr': 62298, 'offers': 65890, 'vivid': 100624, 'portrait': 71935, 'human': 44993, 'relations': 76776, 'seems': 82314, 'telling': 92513, 'power': 72204, 'success': 89881, 'people': 69380, 'different': 25947, 'situations': 84921, 'encounter': 30534, 'variation': 99532, 'arthur': 6493, 'schnitzler': 81470, 'play': 71008, 'theme': 93168, 'director': 26278, 'transfers': 95292, 'action': 2544, 'present': 72669, 'new': 64053, 'york': 104503, 'meet': 59081, 'connect': 20287, 'connected': 20288, 'another': 5292, 'next': 64145, 'person': 69686, 'know': 51848, 'previous': 72816, 'contact': 20578, 'stylishly': 89605, 'sophisticated': 86653, 'luxurious': 56129, 'look': 55383, 'taken': 91617, 'live': 54928, 'world': 103569, 'habitat': 41189, 'gets': 38316, 'souls': 86793, 'picture': 70382, 'stages': 87995, 'loneliness': 55312, 'inhabits': 47123, 'big': 10599, 'best': 10298, 'place': 70838, 'find': 34546, 'sincere': 84716, 'fulfillment': 36855, 'discerns': 26430, 'case': 15728, 'acting': 2533, 'good': 39408, 'direction': 26267, 'steve': 88647, 'buscemi': 14217, 'rosario': 79217, 'dawson': 23707, 'carol': 15541, 'kane': 50437, 'imperioli': 46107, 'adrian': 2912, 'grenier': 40205, 'rest': 77617, 'talented': 91658, 'cast': 15808, 'come': 19372, 'alive': 3991, 'we': 101692, 'wish': 103062, 'luck': 55848, 'await': 7666, 'anxiously': 5526, 'work': 103520, 'probably': 73017, 'all': 4003, 'favorite': 33648, 'story': 88993, 'selflessness': 82448, 'sacrifice': 80056, 'dedication': 24150, 'noble': 64605, 'cause': 16070, 'preachy': 72361, 'boring': 12322, 'despite': 25323, 'seen': 82318, '15': 313, 'times': 94029, 'last': 53236, '25': 890, 'paul': 68863, 'lukas': 55925, 'performance': 69500, 'brings': 13231, 'tears': 92271, 'eyes': 32816, 'bette': 10361, 'davis': 23680, 'sympathetic': 91245, 'roles': 78979, 'delight': 24564, 'kids': 51256, 'are': 6105, 'grandma': 39896, 'says': 81044, 'dressed': 28268, 'up': 98818, 'midgets': 60003, 'children': 17374, 'makes': 56887, 'fun': 36902, 'mother': 62006, 'slow': 85574, 'awakening': 7674, 'what': 102189, 'happening': 41820, 'roof': 79129, 'believable': 9826, 'startling': 88288, 'dozen': 28013, 'thumbs': 93763, 'sure': 90571, 'resurrection': 77694, 'dated': 23608, 'seahunt': 82051, 'series': 82802, 'tech': 92292, 'today': 94344, 'bring': 13225, 'back': 7969, 'kid': 51218, 'excitement': 32171, 'grew': 40223, 'black': 11007, 'white': 102413, 'tv': 96548, 'gunsmoke': 40956, 'hero': 43143, 'week': 101812, 'you': 104537, 'vote': 100826, 'comeback': 19373, 'sea': 82024, 'hunt': 45154, 'need': 63705, 'change': 16647, 'pace': 67730, 'water': 101554, 'adventure': 2966, 'oh': 65987, 'thank': 92996, 'outlet': 67127, 'view': 100220, 'viewpoints': 100234, 'movies': 62226, 'ole': 66138, 'believe': 9829, 'wanna': 101286, 'nice': 64197, 'read': 75659, 'plus': 71272, 'points': 71401, 'if': 45672, 'rhymes': 78140, 'lines': 54682, 'let': 54111, 'submit': 89727, 'or': 66581, 'leave': 53663, 'doubt': 27873, 'quit': 74675, 'lets': 54134, 'amazing': 4427, 'fresh': 36474, 'innovative': 47272, 'idea': 45559, '70': 1414, 'aired': 3550, 'brilliant': 13202, 'dropped': 28388, 'that': 93018, '1990': 664, 'funny': 36976, 'anymore': 5541, 'continued': 20687, 'decline': 24074, 'complete': 19730, 'waste': 101491, 'disgraceful': 26604, 'fallen': 33131, 'writing': 103804, 'painfully': 67877, 'bad': 8067, 'performances': 69501, 'almost': 4176, 'mildly': 60161, 'entertaining': 30947, 'respite': 77584, 'guest': 40720, 'hosts': 44636, 'hard': 41874, 'creator': 21966, 'hand': 41635, 'selected': 82427, 'original': 66750, 'also': 4247, 'chose': 17658, 'band': 8488, 'hacks': 41227, 'followed': 35539, 'recognize': 76019, 'brilliance': 13200, 'fit': 34785, 'replace': 77226, 'mediocrity': 59024, 'felt': 33921, 'give': 38772, 'stars': 88263, 'respect': 77564, 'made': 56511, 'huge': 44929, 'now': 65106, 'awful': 7713, 'can': 14963, 'encouraged': 30541, 'positive': 71994, 'comments': 19508, 'looking': 55392, 'forward': 35975, 'mistake': 60846, '950': 1577, 'films': 34465, 'worst': 103633, 'pacing': 67761, 'storyline': 89009, 'soundtrack': 86824, 'song': 86568, 'lame': 52869, 'country': 21525, 'tune': 96352, 'played': 71020, 'less': 54092, 'four': 36048, 'looks': 55399, 'cheap': 16978, 'extreme': 32743, 'rarely': 75361, 'happy': 41839, 'end': 30567, 'credits': 21993, 'prevents': 72808, 'giving': 38784, 'score': 81704, 'harvey': 42119, 'keitel': 50892, 'least': 53642, 'making': 56900, 'bit': 10922, 'effort': 29595, 'obsessives': 65616, 'only': 66308, 'gut': 41017, 'wrenching': 103743, 'laughter': 53369, 'hell': 42850, 'mom': 61288, 'liked': 54508, 'camp': 14910, 'phil': 70063, 'alien': 3943, 'quirky': 74668, 'humour': 45083, 'based': 8944, 'oddness': 65786, 'everything': 31941, 'actual': 2592, 'punchlines': 74001, 'at': 6995, 'odd': 65776, 'progressed': 73218, 'jokes': 49723, 'its': 48607, 'low': 55717, 'budget': 13756, 'problem': 73036, 'itself': 48608, 'eventually': 31884, 'lost': 55548, 'interest': 47704, 'imagine': 45896, 'stoner': 88898, 'currently': 22807, 'partaking': 68510, 'for': 35660, 'something': 86507, 'better': 10362, 'try': 96153, 'brother': 13471, 'planet': 70903, '12': 223, 'came': 14846, 'out': 67042, 'recall': 75899, 'scariest': 81178, 'scene': 81252, 'bird': 10839, 'eating': 29240, 'men': 59333, 'dangling': 23382, 'helplessly': 42924, 'parachutes': 68241, 'horror': 44531, 'as': 6584, 'cheesy': 17101, 'saturday': 80883, 'afternoons': 3226, 'tired': 94166, 'formula': 35882, 'monster': 61505, 'type': 96724, 'usually': 99089, 'included': 46485, 'beautiful': 9412, 'might': 60061, 'daughter': 23631, 'professor': 73154, 'resolution': 77530, 'died': 25903, 'care': 15369, 'much': 62355, 'romantic': 79046, 'angle': 5061, 'year': 104279, 'predictable': 72459, 'plots': 71194, 'unintentional': 98060, 'humor': 45072, 'but': 14298, 'later': 53269, 'psycho': 73744, 'loved': 55674, 'star': 88186, 'janet': 48947, 'leigh': 53868, 'bumped': 13978, 'early': 29143, 'sat': 80796, 'took': 94613, 'notice': 65011, 'since': 84715, 'screenwriters': 81858, 'scary': 81204, 'possible': 72027, 'worn': 103600, 'rules': 79688, 'im': 45872, 'fan': 33223, 'boll': 11914, 'enjoyed': 30775, 'postal': 72033, 'maybe': 58403, 'apparently': 5730, 'bought': 12472, 'rights': 78377, 'cry': 22514, 'long': 55324, 'ago': 3351, 'game': 37408, 'finsished': 34639, 'killing': 51344, 'mercs': 59502, 'infiltrating': 46972, 'secret': 82192, 'research': 77426, 'labs': 52628, 'located': 55113, 'tropical': 95984, 'island': 48461, 'warned': 101376, 'schemed': 81342, 'together': 94385, 'along': 4195, 'legion': 53813, 'schmucks': 81456, 'feeling': 33815, 'loneley': 55309, 'invites': 48150, 'three': 93631, 'countrymen': 21528, 'with': 103119, 'players': 71024, 'names': 63200, 'til': 93956, 'schweiger': 81605, 'udo': 96852, 'kier': 51271, 'ralf': 75107, 'moeller': 61151, 'actually': 2598, 'selfs': 82451, 'biz': 10964, 'tale': 91655, 'jack': 48738, 'carver': 15701, 'yes': 104367, 'german': 38231, 'hail': 41339, 'bratwurst': 12848, 'dudes': 28593, 'however': 44784, 'tils': 93975, 'badass': 8076, 'complained': 19715, 'staying': 88381, 'true': 96076, 'whole': 102500, 'perspective': 69728, 'looked': 55386, 'kicking': 51213, 'beyond': 10437, 'demented': 24686, 'evil': 31977, 'mad': 56476, 'scientist': 81633, 'dr': 28031, 'krieger': 52239, 'genetically': 38046, 'mutated': 62835, 'soldiers': 86372, 'gms': 39077, 'performing': 69510, 'top': 94669, 'reminds': 76967, 'spoiler': 87494, 'vancouver': 99420, 'reason': 75798, 'palm': 67996, 'trees': 95601, 'here': 43082, 'rich': 78186, 'lumberjack': 55951, 'woods': 103407, 'gone': 39384, 'started': 88279, 'mehehe': 59137, 'cannot': 15087, 'stay': 88377, 'bolls': 11925, 'shenanigans': 83549, 'delivers': 24598, 'meaning': 58874, 'suck': 89915, 'mentioning': 59439, 'imply': 46182, 'areas': 6111, 'boat': 11670, 'cromed': 22281, 'albino': 3782, 'squad': 87778, 'enters': 30936, 'laugh': 53350, 'reeks': 76322, 'scheisse': 81331, 'poop': 71731, 'simpletons': 84665, 'fa': 32861, 'take': 91608, 'wiff': 102672, 'ahead': 3430, 'btw': 13661, 'annoying': 5257, 'sidekick': 84373, 'shoot': 83922, 'minutes': 60518, 'screen': 81838, 'shakespeare': 83164, 'appreciate': 5848, 'trying': 96158, 'masses': 58029, 'ruin': 79665, 'is': 48380, 'scottish': 81745, 'certain': 16417, 'rev': 77852, 'bowdler': 12551, 'hence': 42976, 'bowdlerization': 12554, 'tried': 95768, 'victorian': 100124, 'era': 31252, 'in': 46321, 'words': 103506, 'improve': 46275, 'perfection': 69477, 'write': 103790, 'ten': 92592, 'text': 92931, 'and': 4859, 'english': 30721, 'composition': 19802, 'forte': 35929, 'keep': 50853, 'saying': 81034, 'cut': 22899, 'fantastic': 33313, 'prisoners': 72952, 'famous': 33220, 'george': 38173, 'clooney': 18639, 'roll': 78987, 'man': 57131, 'constant': 20494, 'sorrow': 86728, 'recommand': 76044, 'everybody': 31930, 'greetings': 40176, 'bart': 8897, 'kind': 51407, 'drawn': 28168, 'erotic': 31358, 'amateurish': 4407, 'unbelievable': 97192, 'bits': 10941, 'sort': 86734, 'school': 81496, 'project': 73240, 'rosanna': 79214, 'arquette': 6373, 'thinking': 93430, 'stock': 88830, 'bizarre': 10966, 'supposed': 90513, 'midwest': 60040, 'town': 94999, 'involved': 48165, 'lessons': 54101, 'learned': 53624, 'insights': 47384, 'stilted': 88743, 'quite': 74676, 'ridiculous': 78278, 'lots': 55568, 'skin': 85095, 'intrigues': 47990, 'videotaped': 100171, 'nonsense': 64789, 'bisexual': 10897, 'relationship': 76777, 'nowhere': 65114, 'heterosexual': 43269, 'encounters': 30538, 'absurd': 2159, 'dance': 23323, 'stereotyped': 88607, 'pass': 68616, 'million': 60260, 'miles': 60170, 'wasted': 101494, 'could': 21433, 'spent': 87240, 'starving': 88298, 'aids': 3486, 'africa': 3195, 'simply': 84679, 'remade': 76890, 'fails': 33029, 'capture': 15282, 'flavor': 35019, 'terror': 92810, '1963': 616, 'title': 94221, 'liam': 54267, 'neeson': 63728, 'excellent': 32123, 'always': 4340, 'holds': 43984, 'exception': 32138, 'owen': 67629, 'wilson': 102829, 'feel': 33811, 'character': 16734, 'luke': 55927, 'major': 56858, 'fault': 33613, 'version': 99946, 'strayed': 89183, 'shirley': 83784, 'jackson': 48776, 'attempts': 7175, 'grandiose': 39890, 'thrill': 93654, 'earlier': 29138, 'trade': 95117, 'snazzier': 85929, 'special': 87102, 'effects': 29570, 'enjoy': 30770, 'friction': 36517, 'older': 66117, 'horrible': 44509, 'continuous': 20695, 'minute': 60514, 'fight': 34308, 'chance': 16616, 'development': 25537, 'busy': 14293, 'running': 79754, 'sword': 91140, 'emotional': 30365, 'attachment': 7152, 'except': 32134, 'machine': 56382, 'wanted': 101296, 'destroy': 25369, 'blatantly': 11203, 'stolen': 88871, 'lotr': 55567, 'wars': 101420, 'matrix': 58238, 'examples': 32091, 'ghost': 38394, 'final': 34516, 'yoda': 104441, 'obee': 65471, 'vader': 99232, 'spider': 87283, 'beginning': 9674, 'frodo': 36641, 'attacked': 7157, 'return': 77823, 'kings': 51461, 'elijah': 29981, 'wood': 103372, 'victim': 100108, 'wait': 101089, 'hypnotizes': 45398, 'stings': 88766, 'wraps': 103719, 'uh': 96904, 'hello': 42879, 'vs': 100880, 'humans': 45027, 'terminator': 92751, 'someone': 86488, 'tell': 92506, 'nazi': 63572, 'juvenile': 50195, 'line': 54665, 'rushed': 79789, 'conclusion': 19975, 'adult': 2931, 'either': 29770, 'disappointment': 26365, 'save': 80958, 'remember': 76941, 'cinema': 17980, 'dark': 23487, 'places': 70847, 'nervous': 63928, '74': 1444, '75': 1451, 'dad': 23102, 'sister': 84881, 'newbury': 64063, 'berkshire': 10169, 'england': 30713, 'tigers': 93927, 'snow': 86073, 'appearance': 5746, 'grizzly': 40391, 'adams': 2644, 'actor': 2574, 'dan': 23317, 'haggery': 41299, 'think': 93423, 'shot': 84003, 'dies': 25920, 'anyone': 5543, 'knows': 51868, 'dvd': 28962, 'etc': 31660, 'please': 71092, 'fitness': 34789, 'club': 18710, 'shame': 83224, 'nearest': 63621, '20': 716, 'hear': 42539, 'others': 66962, 'stinkers': 88779, 'nominated': 64710, 'golden': 39287, 'globe': 38984, 'female': 33924, 'renaissance': 77027, 'painter': 67890, 'mangled': 57240, 'recognition': 76015, 'complaint': 19720, 'liberties': 54312, 'facts': 32973, 'perfectly': 69482, 'fine': 34556, 'accounts': 2339, 'artist': 6532, 'dishwater': 26647, 'dull': 28676, 'script': 81897, 'suppose': 90511, 'enough': 30830, 'naked': 63170, 'factual': 32974, 'hurriedly': 45199, 'capped': 15224, 'summary': 90154, 'saved': 80959, 'couple': 21545, 'hours': 44704, 'favored': 33644, 'brevity': 13072, 'die': 25901, 'sequels': 82717, 'surprise': 90647, '1990s': 666, 'glut': 39057, 'cashed': 15742, 'wrong': 103812, 'guy': 41045, 'concept': 19920, 'cliffhanger': 18514, 'mountain': 62107, 'rescue': 77418, 'sly': 85646, 'stop': 88931, 'stallone': 88085, 'nit': 64536, 'pickers': 70342, 'especially': 31521, 'expert': 32477, 'climbing': 18545, 'base': 8941, 'jumping': 50074, 'aviation': 7610, 'facial': 32930, 'expressions': 32616, 'full': 36861, 'excuses': 32235, 'dismiss': 26724, 'overblown': 67299, 'pile': 70500, 'junk': 50106, 'acted': 2527, 'horse': 44553, 'lovable': 55660, 'undeniably': 97420, 'romp': 79091, 'plenty': 71133, 'thrills': 93664, 'unintentionally': 98061, 'laughs': 53367, 've': 99637, 'john': 49676, 'lithgows': 54876, 'sneery': 85953, 'evilness': 31987, 'tick': 93861, 'box': 12592, 'baddies': 8090, 'permanently': 69580, 'harassed': 41854, 'hapless': 41810, 'turncoat': 96448, 'agent': 3277, 'rex': 78046, 'linn': 54722, 'travers': 95511, 'he': 42439, 'henry': 43025, 'rooker': 79137, 'noteworthy': 64998, 'cringe': 22126, 'worthy': 103646, 'hal': 41406, 'insists': 47409, 'constantly': 20499, 'shrieking': 84133, 'painful': 67875, 'disbelief': 26408, 'captors': 15281, 'hurt': 45209, 'anybody': 5532, 'whilst': 102325, 'surely': 90574, 'be': 9268, 'ralph': 75114, 'waite': 101090, 'frank': 36206, 'grinning': 40343, 'girl': 38699, 'plummets': 71244, 'mention': 59436, 'former': 35873, 'london': 55301, 'burning': 14151, 'craig': 21783, 'fairbrass': 33044, 'brit': 13264, 'cropper': 22318, 'using': 99070, 'football': 35618, 'help': 42912, 'needed': 63706, 'judgement': 49970, 'cares': 15402, 'happen': 41815, 'lower': 55728, 'expectations': 32421, 'turn': 96442, 'volume': 100761, 'qaulen': 74330, 'wearing': 101729, 'helicopter': 42842, 'terrible': 92783, 'misfortune': 60684, 'entirety': 30986, 'aspects': 6747, 'paper': 68195, 'thin': 93404, 'sequences': 82722, 'fake': 33082, 'packed': 67774, 'crappy': 21846, 'liners': 54

In [30]:
sum=0

for keys in cv.vocabulary_.values():
  sum+=int(keys)
sum

5544940086

In [31]:
bow.shape

(50000, 105309)

In [32]:
bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [33]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary

In [34]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python
total_words=0
c=0
for review in df['review']:
  total_words+=len(review.split())
total_words

6126659

In [35]:
vocabulary = set()

for review in df['review']:
    vocabulary.update(review.split())

print(len(vocabulary))

423159

In [36]:
# Problem 3

# Apply One Hot Encoding

In [37]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [38]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

cv2=CountVectorizer(ngram_range=(3,3))

In [39]:
bow2=cv2.fit_transform(df['review'])

In [40]:
len(cv2.vocabulary_)

5681821

In [41]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
tfidf=TfidfVectorizer()

In [ ]:
tfidf.fit_transform(df['review']).toarray()